name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  NuGetDirectory: ${{ github.workspace }}/Artifacts

defaults:
  run:
    shell: pwsh

jobs:
  create_package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Version
      uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  deploy:

    runs-on: ubuntu-latest

    needs: [ create_package ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: ${{ env.NuGetDirectory }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
